// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Swagger lob
//
//  A sample for LOB API
//  Schemes:
//    http
//  Host: localhost:8000
//  BasePath: /api
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
